config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :list, presence: true
  validates :list, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_bookmark, only: %i[destroy]
  before_action :find_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    list = @bookmark.list
    @bookmark.destroy

    redirect_to list_path(list), status: :see_other
  end

  private

  def find_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def find_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save

    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmark#destroy</h1>
<p>Find me in app/views/bookmark/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmark#new</h1>
<p>Find me in app/views/bookmark/new.html.erb</p>

<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.input :movie_id, collection: @movies %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>List#index</h1>

<div class="header">
  <h1>Voici vos liste de film</h1>
  <%= link_to "add", new_list_path, class: "button"%>
</div>

<div class="list">
  <% @lists.each do |list| %>
  <div class="card">
    <%= link_to list_path(list), class: "card--clickable" do %>
        <% if list.photo.attached? %>
          <%= cl_image_tag list.photo.key, class: "card--image" %>
        <% end %>
        <div class="card--infos">
          <h1><%= list.name %></h1>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>List#new</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<%end%>

app/views/lists/show.html.erb
<div class="header">
  <h1><%=@list.name%></h1>
  <%= link_to "add", new_list_bookmark_path(@list), class: "button"%>
</div>

<div class="list">
  <% @list.bookmarks.each do |bookmark| %>
  <div class="card">
    <div class="card--image" style="background-image: url('<%= bookmark.movie.poster_url %>'"></div>
    <div class="card--infos">
      <h1><%= bookmark.movie.title %></h1>
      <div class="card--infos--right">
        <p class="card--infos--tag"><%= bookmark.comment %></p>
        <%= link_to "delete",
        bookmark_path(bookmark), class: "button",
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
        %>
      </div>
    </div>
  </div>
  <% end %>
</div>